package com.bootcamp.finalproyect.CRUDS;

// default package
// Generated 14/02/2015 16:19:18 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Compra generated by hbm2java
 */
public class Compra implements java.io.Serializable {

	private int idCompra;
	private Date fecha;
	private char estado;

	public Compra() {
	}

	public Compra(int idCompra, Date fecha, char estado) {
		this.idCompra = idCompra;
		this.fecha = fecha;
		this.estado = estado;
	}

	public int getIdCompra() {
		return this.idCompra;
	}

	public void setIdCompra(int idCompra) {
		this.idCompra = idCompra;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public char getEstado() {
		return this.estado;
	}

	public void setEstado(char estado) {
		this.estado = estado;
	}

}
