package com.bootcamp.finalproyect.CRUDS;

// default package
// Generated 14/02/2015 16:19:18 by Hibernate Tools 3.4.0.CR1

/**
 * Fomapago generated by hbm2java
 */
public class Fomapago implements java.io.Serializable {

	private int idFomaPago;
	private String pago;

	public Fomapago() {
	}

	public Fomapago(int idFomaPago) {
		this.idFomaPago = idFomaPago;
	}

	public Fomapago(int idFomaPago, String pago) {
		this.idFomaPago = idFomaPago;
		this.pago = pago;
	}

	public int getIdFomaPago() {
		return this.idFomaPago;
	}

	public void setIdFomaPago(int idFomaPago) {
		this.idFomaPago = idFomaPago;
	}

	public String getPago() {
		return this.pago;
	}

	public void setPago(String pago) {
		this.pago = pago;
	}

}
