package com.bootcamp.finalproyect.CRUDS;

// default package
// Generated 14/02/2015 16:19:18 by Hibernate Tools 3.4.0.CR1

/**
 * ProductosId generated by hbm2java
 */
public class ProductosId implements java.io.Serializable {

	private int idProductos;
	private int idCategoria;

	public ProductosId() {
	}

	public ProductosId(int idProductos, int idCategoria) {
		this.idProductos = idProductos;
		this.idCategoria = idCategoria;
	}

	public int getIdProductos() {
		return this.idProductos;
	}

	public void setIdProductos(int idProductos) {
		this.idProductos = idProductos;
	}

	public int getIdCategoria() {
		return this.idCategoria;
	}

	public void setIdCategoria(int idCategoria) {
		this.idCategoria = idCategoria;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProductosId))
			return false;
		ProductosId castOther = (ProductosId) other;

		return (this.getIdProductos() == castOther.getIdProductos())
				&& (this.getIdCategoria() == castOther.getIdCategoria());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdProductos();
		result = 37 * result + this.getIdCategoria();
		return result;
	}

}
