package com.bootcamp.finalproyect.CRUDS;

// default package
// Generated 14/02/2015 16:19:18 by Hibernate Tools 3.4.0.CR1

/**
 * Productos generated by hbm2java
 */
public class Productos implements java.io.Serializable {

	private ProductosId id;
	private Categoria categoria;
	private String nombre;
	private String precio;
	private String detalle;

	public Productos() {
	}

	public Productos(ProductosId id, Categoria categoria, String nombre,
			String precio) {
		this.id = id;
		this.categoria = categoria;
		this.nombre = nombre;
		this.precio = precio;
	}

	public Productos(ProductosId id, Categoria categoria, String nombre,
			String precio, String detalle) {
		this.id = id;
		this.categoria = categoria;
		this.nombre = nombre;
		this.precio = precio;
		this.detalle = detalle;
	}

	public ProductosId getId() {
		return this.id;
	}

	public void setId(ProductosId id) {
		this.id = id;
	}

	public Categoria getCategoria() {
		return this.categoria;
	}

	public void setCategoria(Categoria categoria) {
		this.categoria = categoria;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getPrecio() {
		return this.precio;
	}

	public void setPrecio(String precio) {
		this.precio = precio;
	}

	public String getDetalle() {
		return this.detalle;
	}

	public void setDetalle(String detalle) {
		this.detalle = detalle;
	}

}
